### ISSUE TITLE
Got a problem

### ISSUE THREAD

**Issue by kunichiu** [kwea123/Unity_live_caption#1]
我在Mac上得到下面的訊息，可以麻煩您解答嗎？謝謝！

(base) KUNde-iMac:Unity_live_caption kun$ python googlesr.py --debug --lang_code={en-US}
Traceback (most recent call last):
  File "googlesr.py", line 2, in <module>
    from google.cloud.speech import SpeechClient, types, enums
ImportError: cannot import name 'types' from 'google.cloud.speech' (/Users/kun/opt/anaconda3/lib/python3.8/site-packages/google/cloud/speech/__init__.py)

**Comment by kwea123** [comment]
updated to the latest `google-cloud-speech` version. Please pull the code and try again
